### ISSUE TITLE
The "Under Contract" link gives edit access to the document.

### ISSUE THREAD

**Issue by ignamiranda** [Billiam/awesome-ironsworn#7]
Replace with this link to avoid it getting griefed https://docs.google.com/document/d/1K1Cr1F1MABw8h-Hm-YL7DH4V9VLmq2Ezn9PEcOsuw-o/edit?usp=sharing

**Comment by Billiam** [comment]
I believe edit vs view permissions for google doc general access are controlled at the document level, rather than allowing edit vs view-only links.

Have you requested edit access to the document already? I don't have edit access, for instance.

**Comment by ignamiranda** [comment]
I hadn't requested edit access. I just checked though and I no longer have edit access. I guess the owner changed something.
