### ISSUE TITLE
NO MAN'S LAND link is dead, can be found on the Wayback Machine

### ISSUE THREAD

**Issue by ignamiranda** [Billiam/awesome-ironsworn#8]
Here is the archived link https://web.archive.org/web/20210918175852/https://drive.google.com/uc?id=1oxzbAmsXef4SISen0j9WlksnV6XXXIBB&export=download

**Comment by Billiam** [comment]
Link doesn't work for me, but since the author has deleted it, it's better to remove it anyway.
